[build]
  command = "npm install && npm run build"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/server-00001/*"
  to = "/.netlify/functions/server-00001/:splat"
  status = 200
